---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: automate
    run_list:
      - recipe[testkitchen::automate]
    driver:
      vm_hostname: automate
      network:
        - ["private_network", {ip: "192.168.33.35"}]
      customize:
        memory: 2048
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    excludes:
      - ubuntu-18.04

  - name: centos
    run_list:
      - recipe[testkitchen::node]
    driver:
      vm_hostname: centos
      network:
        - ["private_network", {ip: "192.168.33.36"}]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    excludes:
      - ubuntu-18.04

  # - name: ubuntu-16.04
  #   driver:
  #     vm_hostname: ubuntu
  #     network:
  #       - ["private_network", {ip: "192.168.33.37"}]
  # - name: windows2016
  #   driver_config:
  #     box: mwrock/Windows2016
  #   driver:
  #     vm_hostname: windows
  #     network:
  #       - ["private_network", {ip: "192.168.33.38"}]
  #     customize:
  #       memory: 2048
  #     boot_timeout: 1200
  #     gui: false